name: Metrics

on:
  schedule:
    - cron: "17 4 * * *"
      timezone: "Europe/Warsaw"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate GitHub profile metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

          user: MichalPlanetaDev
          template: classic

          base: header, activity, repositories, metadata
          base_hireable: yes
          base_skip: no
          commits_authoring: MichalPlanetaDev

          config_octicon: yes
          config_padding: 20, 8 + 11%
          config_presets: "@lunar-red"
          config_timezone: Europe/Warsaw
          config_twemoji: yes

          plugin_introduction: yes
          plugin_introduction_title: yes

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_limit: 6
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories

          plugin_repositories: yes
          plugin_repositories_featured: tickline, anticheat-portfolio, rust-security-sandbox, afterlight
          plugin_repositories_order: featured, pinned, starred, random
          plugin_repositories_pinned: 0

          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: "76561198302989920"
          plugin_steam_achievements_limit: 0
          plugin_steam_games_limit: 3
          plugin_steam_playtime_threshold: 1
          plugin_steam_recent_games_limit: 3
          plugin_steam_sections: player, most-played, recently-played

          plugin_music: no

          plugin_16personalities: no

          plugin_achievements: no
